apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog-forwarder
spec:
  selector:
    matchLabels:
      app: rsyslog-forwarder
  template:
    metadata:
      labels:
        app: rsyslog-forwarder
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      containers:
      - name: rsyslog-forwarder
        image: w0n9/rsyslog-forwarder
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: rsyslog-tcp
          containerPort: 514
          protocol: TCP
        - name: rsyslog-udp
          containerPort: 514
          protocol: UDP
        volumeMounts:
        - name: rsyslog-conf
          mountPath: /etc/rsyslog.conf
          subPath: rsyslog.conf
          readOnly: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
      - name: rsyslog-conf
        configMap:
          name: rsyslog-conf
          optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: rsyslog-forwarder
spec:
  type: LoadBalancer
  selector:
    app: rsyslog-forwarder
  ports:
  - name: rsyslog-tcp
    port: 514
    protocol: TCP
    targetPort: rsyslog-tcp
  - name: rsyslog-udp
    port: 514
    protocol: UDP
    targetPort: rsyslog-udp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rsyslog-conf
data:
  rsyslog.conf: >
    #https://www.rsyslog.com/doc/v8-stable/concepts/multi_ruleset.html#split-local-and-remote-logging


    ruleset(name="remote"){
      # https://www.rsyslog.com/doc/v8-stable/configuration/modules/omfwd.html
      # https://grafana.com/docs/loki/latest/clients/promtail/scraping/#rsyslog-output-configuration
      action(type="omfwd" Target="localhost" Port="1514" Protocol="tcp" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted")
    }




    # https://www.rsyslog.com/doc/v8-stable/configuration/modules/imudp.html


    module(load="imudp")


    input(type="imudp" port="514" ruleset="remote")



    # https://www.rsyslog.com/doc/v8-stable/configuration/modules/imtcp.html


    module(load="imtcp")


    input(type="imtcp" port="514" ruleset="remote")


